// File generated by FlutterFire CLI / configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase.initializeApp.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running "flutterfire configure"',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYlQZ2OZs7h0LD7E0yopHEmSxMObUO2_g',
    appId: '1:1059909693916:web:3e5f3e4eedad807c13df19',
    messagingSenderId: '1059909693916',
    projectId: 'galaxi-gadai',
    authDomain: 'galaxi-gadai.firebaseapp.com',
    storageBucket: 'galaxi-gadai.firebasestorage.app',
    measurementId: 'G-M8GN8J3VEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKjCy7YTjFqCDyhocYGrw2g-Xq2XPLwm4',
    appId: '1:1059909693916:android:8b75347eaad2a9d413df19',
    messagingSenderId: '1059909693916',
    projectId: 'galaxi-gadai',
    storageBucket: 'galaxi-gadai.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM1DUywOhclrDFhbYeZQOYEoUgIrCkDu0',
    appId: '1:1059909693916:ios:38ea974496fcf12d13df19',
    messagingSenderId: '1059909693916',
    projectId: 'galaxi-gadai',
    storageBucket: 'galaxi-gadai.firebasestorage.app',
    iosBundleId: 'com.example.galaxiGadai',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM1DUywOhclrDFhbYeZQOYEoUgIrCkDu0',
    appId: '1:1059909693916:ios:38ea974496fcf12d13df19',
    messagingSenderId: '1059909693916',
    projectId: 'galaxi-gadai',
    storageBucket: 'galaxi-gadai.firebasestorage.app',
    iosBundleId: 'com.example.galaxiGadai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYlQZ2OZs7h0LD7E0yopHEmSxMObUO2_g',
    appId: '1:1059909693916:web:1208d2185ebd050b13df19',
    messagingSenderId: '1059909693916',
    projectId: 'galaxi-gadai',
    authDomain: 'galaxi-gadai.firebaseapp.com',
    storageBucket: 'galaxi-gadai.firebasestorage.app',
    measurementId: 'G-73REZ8MKJM',
  );
}
